# Generated by Django 5.0.1 on 2024-03-01 15:51

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Теги поста:')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Тег записи',
                'verbose_name_plural': 'Теги записей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('slag', models.SlugField(default=0, max_length=250, verbose_name='Ссылка')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='news.category')),
            ],
            options={
                'verbose_name': 'Категория записи',
                'verbose_name_plural': 'Категории записей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Ссылка')),
                ('excerpt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Анонс')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_blocks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовые блоки')),
                ('text_img', models.ImageField(default='default/bblog1.png', upload_to='news_images/', verbose_name='Главное изображение записи')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='news.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_galleries/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя оставившего отзыв')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text_rev', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Отзыв')),
                ('vork_user', models.CharField(default=1, max_length=100, verbose_name='Должность')),
                ('news_perent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_res', models.CharField(max_length=100, verbose_name='Имя оставившего ответ')),
                ('email_res', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text_rev_res', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('vork_user_res', models.CharField(max_length=100, null=True, verbose_name='Должность')),
                ('news_perent_res', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
                ('parent_review_res', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.reviews', verbose_name='Родительский отзыв')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
