# Generated by Django 5.0.2 on 2024-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.133.203', verbose_name='IP адрес публикации'),
        ),
    ]
