# Generated by Django 5.0.2 on 2024-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneservices',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Одна услуга'},
        ),
        migrations.AddField(
            model_name='oneservices',
            name='descriptionServices',
            field=models.TextField(default=0, max_length=250, verbose_name='Краткое описание услуги'),
            preserve_default=False,
        ),
    ]
