# Generated by Django 5.0.2 on 2024-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(max_length=500, verbose_name='Заголовок над формой')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('email_site', models.EmailField(max_length=254, verbose_name='Почта на сайте')),
                ('adress_local', models.CharField(max_length=1000, verbose_name='Адрес указанный на сайте')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('massage', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('create_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
