# Generated by Django 5.0.2 on 2024-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikons', models.CharField(help_text='Иконки берем из этого пака <a href="https://icons.getbootstrap.com/"> Иконки для сайта</a>', max_length=200, verbose_name='Класс иконки')),
                ('link', models.URLField(help_text='Ссылка вставляется полная', verbose_name='Ссылка на соц сеть')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Данные для страниц', 'verbose_name_plural': 'Данные для страниц'},
        ),
        migrations.AlterModelOptions(
            name='contactsmodal',
            options={'verbose_name': 'Заявка с формы', 'verbose_name_plural': 'Заявки с формы'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.IntegerField(max_length=200, verbose_name='Номер телефона'),
        ),
    ]
