# Generated by Django 5.0.2 on 2024-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_sociallinks_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='ikons',
            field=models.CharField(help_text='Иконки берем из этого пака <a href="https://icons.getbootstrap.com/" target="blank"> Иконки для сайта</a>', max_length=200, verbose_name='Класс иконки'),
        ),
    ]
