# Generated by Django 5.0.2 on 2024-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_sociallinks_options_alter_sociallinks_ikons'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_text', models.TextField(max_length=200, verbose_name='Текст над заголовком')),
                ('h1_site', models.TextField(max_length=200, verbose_name='Заголовок сайта')),
                ('color_text', models.TextField(help_text='Важно! Заполнять только одно слово', verbose_name='Текст с цветом')),
                ('image', models.ImageField(default='default/bsmall1.png', upload_to='home/', verbose_name='Изображение на первом экране')),
            ],
            options={
                'verbose_name': 'Первый экран',
                'verbose_name_plural': 'Первый экран',
            },
        ),
        migrations.AlterField(
            model_name='contactsmodal',
            name='create_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки'),
        ),
    ]
