# Generated by Django 5.0.2 on 2024-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_hiroblock_alter_contactsmodal_create_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiroblock',
            name='link_yutube',
            field=models.URLField(default=0, verbose_name='Ссылка на ютуб видео'),
            preserve_default=False,
        ),
    ]
