# Generated by Django 5.0.2 on 2024-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_hiroblock_link_yutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiroblock',
            name='mini_text_link',
            field=models.URLField(default=0, verbose_name='Ссылка на первый текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiroblock',
            name='mini_text_str',
            field=models.TextField(default=0, max_length=200, verbose_name='Текст над заголовком вторая строка'),
            preserve_default=False,
        ),
    ]
