# Generated by Django 5.0.2 on 2024-03-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_hiroblock_mini_text_link_hiroblock_mini_text_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_galleries/', verbose_name='Изображение')),
                ('galery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='about.hiroblock', verbose_name='Новость')),
            ],
        ),
    ]
