# Generated by Django 5.0.2 on 2024-03-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_galleryhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Название компании')),
                ('text', models.TextField(help_text='Важно! Заполнять только одно/два слова', max_length=200, verbose_name='Описание в нескольких словах')),
                ('yar', models.IntegerField(verbose_name='Год работы')),
            ],
            options={
                'verbose_name': 'Одна компания',
                'verbose_name_plural': 'Где работал',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryhomepage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='galleryhomepage',
            name='galery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='about.hiroblock', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='galleryhomepage',
            name='image',
            field=models.ImageField(upload_to='block-ty-galery/', verbose_name='Изображение'),
        ),
    ]
