# Generated by Django 5.0.2 on 2024-03-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_ourawards_alter_galleryhomepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStepsHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleWorkSteps', models.TextField(max_length=250, verbose_name='Заголовок блока Этапы работы')),
                ('SubTitleWorkSteps', models.CharField(max_length=200, verbose_name='Подзаголовок который стоит над заголовоком')),
                ('TitleOneStep', models.CharField(max_length=50, verbose_name='Заголовок этапа')),
                ('TextOneStep', models.TextField(max_length=500, verbose_name='Описание этапа')),
                ('LiListOneSteps', models.CharField(max_length=150, verbose_name='Один пункт')),
                ('ListOneSteps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneSteps', to='about.workstepshomepage', verbose_name='Блок')),
                ('WorkSteps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkSteps', to='about.hiroblock', verbose_name='Блок')),
            ],
        ),
    ]
