# Generated by Django 5.0.2 on 2024-03-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_workstepshomepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstepshomepage',
            name='LiListOneSteps',
        ),
        migrations.RemoveField(
            model_name='workstepshomepage',
            name='ListOneSteps',
        ),
        migrations.RemoveField(
            model_name='workstepshomepage',
            name='TextOneStep',
        ),
        migrations.RemoveField(
            model_name='workstepshomepage',
            name='TitleOneStep',
        ),
        migrations.RemoveField(
            model_name='workstepshomepage',
            name='WorkSteps',
        ),
        migrations.CreateModel(
            name='OneStepHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleOneStep', models.CharField(max_length=50, verbose_name='Заголовок этапа')),
                ('TextOneStep', models.TextField(max_length=500, verbose_name='Описание этапа')),
                ('OneStep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneStep', to='about.workstepshomepage', verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='ListOneStepsHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LiListOneSteps', models.CharField(max_length=150, verbose_name='Один пункт')),
                ('ListOneSteps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OneSteps', to='about.onestephomepage', verbose_name='Блок')),
            ],
        ),
    ]
