# Generated by Django 5.0.2 on 2024-03-14 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_workstepshomepage_lilistonesteps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstepshomepage',
            options={'verbose_name': 'Блок шагов', 'verbose_name_plural': 'Шаги работы над проектом'},
        ),
        migrations.AddField(
            model_name='onestephomepage',
            name='ListOneStep',
            field=ckeditor.fields.RichTextField(default=0, help_text='Нужно вставлять верный код!', verbose_name='Пункты списка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListOneStepsHomePage',
        ),
    ]
