# Generated by Django 5.0.2 on 2024-03-14 13:00

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_workstepshomepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigText', models.CharField(max_length=250, verbose_name='Большой текст из подвала')),
                ('footerDesc', models.TextField(max_length=500, verbose_name='Описание сайта в подвале')),
                ('copyrightText', ckeditor.fields.RichTextField(help_text='Можно вставлять ссылки', verbose_name='Копирайт')),
            ],
        ),
        migrations.CreateModel(
            name='polysiFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polysiTitle', models.CharField(max_length=250, verbose_name='Название страницы политики')),
                ('polysiUrl', models.URLField(max_length=250, verbose_name='Ссылка на страницу политики')),
                ('polysiFooterItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Политика', to='about.footerinfo', verbose_name='Политики конфиденциальности')),
            ],
        ),
    ]
