# Generated by Django 5.0.2 on 2024-03-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_footerinfo_polysifooter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Информация в подвале', 'verbose_name_plural': 'Информация в подвале'},
        ),
    ]
